"""Render a ``BedrockDeployPlan`` into a self-contained Strands source package.

AgentCore Runtime hosts a container that serves ``POST /invocations`` + ``GET
/ping`` on port 8080. agentlift ships a generated Python package whose
``agent.py`` builds a ``BedrockAgentCoreApp`` around a Strands agent graph. Like
``google_codegen.py`` this module is *pure*: same plan in, same files out, no
network, no clock. ``agent.py`` is the contract the runtime runs.

The generated ``agent.py`` imports ONLY ``strands`` + ``mcp`` + ``bedrock_agentcore``
(never agentlift), so it builds in the runtime's own environment. It exposes:

  - ``app``                : the ``BedrockAgentCoreApp`` (its ``@app.entrypoint``)
  - ``_handle_invocation`` : the plain function the entrypoint delegates to -- the
                             stable hook offline tests drive without AgentCore routing

The load-bearing design choice (settled with the live API probe, 2026-06-04):

  **Request-scoped runtime graph.** Strands ``MCPClient`` is a context manager and
  its tools are only valid while that context is open (calling a tool after exit
  raises ``MCPClientInitializationError``). A hosted runtime serves many requests
  over a process whose freeze/thaw + idle behavior we do not control, so module-
  scope persistent MCP connections are the wrong default (stale half-open sockets,
  no reconnect path, env-token rotation captured at import). Instead each
  ``/invocations`` opens an ``ExitStack``, builds the agent graph inside it, runs the
  root agent, and tears everything down deterministically when it returns. An
  ``_Invocation`` object owns the stack and dedupes MCP clients **by full recipe**
  (url + auth-env names + tool filter + prefix) -- so the same server reused by a
  coordinator and a sub-agent in one request opens one session, but two servers
  that differ in their allowlist stay isolated (the allowlist is a capability
  boundary, so we never share an unfiltered connection).

  **Sub-agents become named ``@tool`` factories.** Each leaf is a generated
  ``_make_<name>_tool(ctx)`` whose inner function (named after the agent, so the
  ``@tool`` spec the model sees carries that name) builds the specialist *inside*
  the same request scope and calls it. The coordinator receives those tools plus
  its own MCP tools. No module-scope agents, no shared mutable state across
  concurrent invocations, no generic recursion (the plan guarantees a depth-1
  roster).

  **MCP tool names are prefixed by server; the allowlist is not.** ``MCPClient`` is
  built with ``prefix=<server>`` (model-facing tools become ``<server>_<tool>``,
  collision-free with the bare sub-agent tool names) and ``tool_filters={"allowed":
  [...]}`` using the RAW folder tool names -- verified: Strands matches the filter
  against the original ``mcp_tool.name``, applying the prefix only to the agent-
  facing rename, so the two compose cleanly.

Secrets are never written here. An MCP auth header reads its value from a named
runtime env var at invocation time (``os.environ.get("AGENTLIFT_MCP_...")``); the
value is populated by the deploy step as an AgentCore env var, not inlined.
"""
from __future__ import annotations

import keyword
import os
from typing import Any

from .bedrock_plan import BedrockAgentNode, BedrockDeployPlan, safe_ident

PACKAGE_NAME = "agentlift_runtime"
MODULE_NAME = f"{PACKAGE_NAME}.agent"
APP_SYMBOL = "app"
HANDLER_SYMBOL = "_handle_invocation"
SKILLS_SUBDIR = "skills"

_HEADER = (
    "Generated by `agentlift deploy --target bedrock` -- DO NOT hand-edit.\n"
    "Edit the .managed-agents/ folder and redeploy. Imports only strands + mcp +\n"
    "bedrock-agentcore so it builds in the AgentCore Runtime container. MCP auth\n"
    "headers read their values from runtime env vars at invocation (never inlined)."
)


# --------------------------------------------------------------------------- #
# python literal helpers
# --------------------------------------------------------------------------- #
def _pystr(s: str) -> str:
    """A triple-quoted Python string literal that always parses.

    Doubles backslashes, escapes any ``\"\"\"`` run, and escapes a trailing quote so
    the content can never collide with the closing delimiter. (Covered by an
    adversarial codegen test.)"""
    body = s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if body.endswith('"'):
        body = body[:-1] + '\\"'
    return '"""' + body + '"""'


def _tool_fn_name(safe_name: str) -> str:
    """The model-facing ``@tool`` function name for a sub-agent.

    Almost always the agent's ``safe_name`` verbatim (so the coordinator's prompt,
    which refers to the agent by name, lines up). Guarded only for the pathological
    case where the name is a Python keyword or otherwise not a valid identifier."""
    if safe_name.isidentifier() and not keyword.iskeyword(safe_name):
        return safe_name
    return "tool_" + safe_name


def _builder_name(node: BedrockAgentNode) -> str:
    return f"_build_{node.safe_name}_agent"


def _factory_name(node: BedrockAgentNode) -> str:
    return f"_make_{node.safe_name}_tool"


# --------------------------------------------------------------------------- #
# per-agent rendering
# --------------------------------------------------------------------------- #
def _mcp_tools_call(recipe) -> str:
    """One ``ctx.mcp_tools(...)`` call as source text.

    The server name doubles as the Strands tool-name prefix; the allowlist passes
    through as RAW folder tool names (the filter matches pre-prefix). Auth headers
    map to {header: env-var-name}; the runtime helper reads the values from env."""
    prefix = safe_ident(recipe.server)
    allowed = repr(list(recipe.tool_filter)) if recipe.tool_filter is not None else "None"
    auth = repr(dict(sorted(recipe.auth_env_vars.items()))) if recipe.auth_env_vars else "{}"
    return (
        f"ctx.mcp_tools(server={recipe.server!r}, url={recipe.url!r}, "
        f"prefix={prefix!r}, allowed={allowed}, auth_env={auth})"
    )


def _agent_builder(node: BedrockAgentNode, sub_nodes: dict[str, BedrockAgentNode]) -> list[str]:
    """The ``_build_<name>_agent(ctx)`` function for one node."""
    lines = [f"def {_builder_name(node)}(ctx):", "    tools = []"]
    # sub-agent delegation tools first (coordinators only)
    for sub in node.sub_agents:
        lines.append(f"    tools.append({_factory_name(sub_nodes[sub])}(ctx))")
    # this agent's own MCP tools
    for recipe in node.mcp:
        lines.append(f"    tools += {_mcp_tools_call(recipe)}")
    plugins = ""
    if node.skills:
        skills = ", ".join(f"_skill({name!r})" for name in node.skills)
        plugins = f"[AgentSkills(skills=[{skills}])]"
    lines += [
        "    return Agent(",
        f"        model=_model({node.bedrock_model!r}),",
        f"        name={node.safe_name!r},",
        f"        system_prompt={_pystr(node.instruction)},",
        f"        description={node.description!r},",
        "        tools=tools,",
    ]
    if plugins:
        lines.append(f"        plugins={plugins},")
    lines += ["    )", "", ""]
    return lines


def _tool_factory(node: BedrockAgentNode) -> list[str]:
    """The ``_make_<name>_tool(ctx)`` factory wrapping a leaf as a delegation tool.

    The inner function is named after the agent so the ``@tool`` spec the model sees
    carries that name; its docstring is the agent's description (routing metadata
    only -- never the full system prompt). It rebuilds the specialist inside the
    live request scope each delegation (MCP dedupe in ``ctx`` keeps that cheap)."""
    fn = _tool_fn_name(node.safe_name)
    return [
        f"def {_factory_name(node)}(ctx):",
        "    @tool",
        f"    def {fn}(task: str) -> str:",
        f"        {_pystr(node.description)}",
        f"        return str({_builder_name(node)}(ctx)(task))",
        f"    return {fn}",
        "",
        "",
    ]


# --------------------------------------------------------------------------- #
# module assembly
# --------------------------------------------------------------------------- #
def _root_and_leaves(plan: BedrockDeployPlan) -> tuple[BedrockAgentNode, list[BedrockAgentNode]]:
    by_name = {n.name: n for n in plan.agents}
    root = by_name[plan.root_agent]
    leaves = [by_name[s] for s in root.sub_agents if s in by_name]
    return root, leaves


def render_agent_py(plan: BedrockDeployPlan) -> str:
    root, leaves = _root_and_leaves(plan)
    sub_nodes = {n.name: n for n in leaves}

    out = [
        '"""' + _HEADER + '"""',
        "import os",
        "from contextlib import ExitStack",
        "",
        "from strands import Agent, AgentSkills, Skill, tool",
        "from strands.models import BedrockModel",
        "from strands.tools.mcp import MCPClient",
        "from mcp.client.streamable_http import streamablehttp_client",
        "from bedrock_agentcore.runtime import BedrockAgentCoreApp",
        "",
        "_HERE = os.path.dirname(os.path.abspath(__file__))",
        f"_SKILLS_DIR = os.path.join(_HERE, {SKILLS_SUBDIR!r})",
        "",
        "# The deploy region is pinned here because the model ids below are regional",
        "# inference profiles (e.g. 'eu.anthropic.*') -- region and model are coupled.",
        f"REGION = {plan.region!r}",
        "",
        "",
        "def _model(model_id):",
        "    return BedrockModel(model_id=model_id, region_name=REGION, temperature=0)",
        "",
        "",
        "def _skill(name):",
        '    return Skill.from_file(os.path.join(_SKILLS_DIR, name, "SKILL.md"))',
        "",
        "",
        "def _extract_prompt(payload):",
        "    if isinstance(payload, dict):",
        '        for key in ("prompt", "input", "text", "query"):',
        "            value = payload.get(key)",
        "            if isinstance(value, str) and value:",
        "                return value",
        "    if isinstance(payload, str):",
        "        return payload",
        "    return str(payload)",
        "",
        "",
        "def _safe_tool_names(result):",
        '    """Best-effort top-level tool-call names for the deploy receipt (delegation',
        "    + any root-level skill/MCP tools). Reads the public AgentResult.metrics",
        "    .tool_metrics; FAIL-OPEN -- trace extraction must never break the invocation,",
        '    so any error returns ([], "<reason>") and the caller still returns the answer."""',
        "    try:",
        '        metrics = getattr(result, "metrics", None)',
        '        tm = getattr(metrics, "tool_metrics", None) or {}',
        "        names = sorted(str(k) for k in tm.keys())",
        "        return names, None",
        "    except Exception as exc:  # noqa: BLE001",
        '        return [], f"{type(exc).__name__}: {exc}"',
        "",
        "",
        "class _Invocation:",
        '    """Request-scoped runtime graph: owns the ExitStack and dedupes MCP clients',
        "    by full recipe (url + auth-env names + allowlist + prefix). Built per",
        "    /invocations, torn down when the root agent returns. No module-scope MCP",
        '    connections (a hosted runtime\'s freeze/thaw makes them go stale)."""',
        "    def __init__(self, stack):",
        "        self._stack = stack",
        "        self._clients = {}",
        "",
        "    def mcp_tools(self, server, url, prefix, allowed, auth_env):",
        "        headers = {h: os.environ.get(env, \"\") for h, env in auth_env.items()}",
        "        key = (url, tuple(sorted(auth_env.items())),",
        "               tuple(allowed) if allowed is not None else None, prefix)",
        "        client = self._clients.get(key)",
        "        if client is None:",
        '            filters = {"allowed": list(allowed)} if allowed is not None else None',
        "            client = MCPClient(",
        "                lambda: streamablehttp_client(url, headers=headers),",
        "                prefix=prefix,",
        "                tool_filters=filters,",
        "            )",
        "            self._stack.enter_context(client)",
        "            self._clients[key] = client",
        "        return list(client.list_tools_sync())",
        "",
        "",
    ]

    # leaves (delegation targets) defined before the coordinator references them
    for leaf in leaves:
        out += _agent_builder(leaf, sub_nodes)
        out += _tool_factory(leaf)
    out += _agent_builder(root, sub_nodes)

    out += [
        f"{APP_SYMBOL} = BedrockAgentCoreApp()",
        "",
        "",
        f"def {HANDLER_SYMBOL}(payload):",
        "    prompt = _extract_prompt(payload)",
        "    with ExitStack() as stack:",
        "        ctx = _Invocation(stack)",
        f"        root = {_builder_name(root)}(ctx)",
        "        result = root(prompt)",
        "        names, trace_error = _safe_tool_names(result)",
        '        body = {"result": str(result)}',
        "        # objective top-level tool-call trace for the deploy receipt (delegation",
        "        # to specialists + any root-level skill/MCP tools). Nested specialist tool",
        "        # calls do NOT cross this boundary -- corroborated by markers in the text.",
        "        if names:",
        '            body["tool_calls"] = names',
        "        if trace_error:",
        '            body["trace_error"] = trace_error',
        "        return body",
        "",
        "",
        f"@{APP_SYMBOL}.entrypoint",
        "def invoke(payload):",
        f"    return {HANDLER_SYMBOL}(payload)",
        "",
        "",
        'if __name__ == "__main__":',
        "    app.run(port=8080)",
        "",
    ]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# package assembly (mirrors google_codegen)
# --------------------------------------------------------------------------- #
def render_text_files(plan: BedrockDeployPlan) -> dict[str, str]:
    """Text files of the build, keyed by relpath from the build root."""
    return {
        f"{PACKAGE_NAME}/__init__.py": "",
        f"{PACKAGE_NAME}/agent.py": render_agent_py(plan),
        "requirements.txt": "\n".join(plan.requirements) + "\n",
    }


def skill_file_manifest(plan: BedrockDeployPlan) -> list[tuple[str, str]]:
    """(relpath_in_build, abs_source) for every skill file shipped into the package.

    arcname already carries the ``<skill-name>/...`` prefix, so it lands under
    ``agentlift_runtime/skills/<skill-name>/...`` -- exactly where ``_skill(name)``
    (``Skill.from_file``) looks for the ``SKILL.md``."""
    out: list[tuple[str, str]] = []
    for bundle in plan.skill_bundles:
        for arcname, abs_path in bundle.files:
            out.append((f"{PACKAGE_NAME}/{SKILLS_SUBDIR}/{arcname}", abs_path))
    return out


def write_package(plan: BedrockDeployPlan, build_dir: str) -> dict[str, Any]:
    """Materialize the package on disk under ``build_dir`` (impure: file IO only).

    Returns the handles the deploy step needs: where the package is, the module +
    symbols the AgentCore Runtime entrypoint targets, and the requirements."""
    os.makedirs(build_dir, exist_ok=True)
    for rel, text in render_text_files(plan).items():
        dest = os.path.join(build_dir, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(text)
    for rel, abs_src in skill_file_manifest(plan):
        dest = os.path.join(build_dir, rel.replace("/", os.sep))
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(abs_src, "rb") as src, open(dest, "wb") as dst:
            dst.write(src.read())
    return {
        "build_dir": build_dir,
        "package_dir": os.path.join(build_dir, PACKAGE_NAME),
        "package_name": PACKAGE_NAME,
        "module_name": MODULE_NAME,
        "app_symbol": APP_SYMBOL,
        "handler_symbol": HANDLER_SYMBOL,
        "requirements": list(plan.requirements),
    }
