"""``agentlift export`` - compile the folder to a provider-native artifact.

Same parsed model as ``deploy``/``audit``; this back-end emits text you hand to a
provider's own tooling instead of deploying through agentlift. Own one neutral
folder, feed each vendor's official toolchain.

Targets:
  anthropic-yaml : per-agent YAML in the Anthropic ``agents.create`` shape - what
                   the official ``ant`` CLI consumes (``ant beta:agents create <
                   x.agent.yaml``). Lossless: Anthropic is the reference target.
  google-adk     : a Google ADK (Agent Engine) Python scaffold. PREVIEW - maps the
                   structure and annotates, inline, every feature the audit flags
                   as degraded/unsupported on Vertex.

Pure, offline. Skill *ids* are assigned at upload (by deploy or ``ant``); the
exported artifacts reference skills by title and the bundles ship alongside.
"""
from __future__ import annotations

import copy

import yaml

from .capabilities import CAPABILITIES
from .planner import DeployPlan

# --------------------------------------------------------------------------- #
# anthropic-yaml  (lossless: the agents.create wire shape == ant's YAML)
# --------------------------------------------------------------------------- #
_ANTHROPIC_HEADER = (
    "# Generated by `agentlift export anthropic-yaml` - do not hand-edit; edit the folder.\n"
    "# This is the Anthropic agents.create shape the official `ant` CLI consumes:\n"
    "#   ant beta:agents create < {name}.agent.yaml\n"
    "# Own the neutral folder; this is the compiled Anthropic artifact. Skills are\n"
    "# referenced by title and uploaded at deploy time (ids assigned then); their\n"
    "# bundles are listed in SKILLS.txt.\n\n"
)


def _clean_request(req: dict, title_by_ref: dict) -> dict:
    """Replace agentlift's symbolic refs with human-readable names for the YAML."""
    r = copy.deepcopy(req)
    if "skills" in r:
        r["skills"] = [title_by_ref.get(s.get("skill_ref"), s.get("skill_ref")) for s in r["skills"]]
    if r.get("multiagent"):
        r["multiagent"] = {
            "type": r["multiagent"]["type"],
            "agents": [a.replace("@agent:", "") for a in r["multiagent"]["agents"]],
        }
    return r


def export_anthropic_yaml(project, plan: DeployPlan) -> dict:
    """Return ``{filename: text}`` - one ``<agent>.agent.yaml`` per agent, plus a
    SKILLS.txt manifest of the bundles to upload."""
    title_by_ref = {u.ref: u.display_title for u in plan.skill_uploads}
    files: dict = {}
    for ac in plan.agent_creates:
        body = _clean_request(ac.request, title_by_ref)
        files[f"{ac.name}.agent.yaml"] = (
            _ANTHROPIC_HEADER.replace("{name}", ac.name)
            + yaml.safe_dump(body, sort_keys=False, width=100, allow_unicode=True)
        )
    if plan.skill_uploads:
        lines = ["# Skill bundles to upload (content-addressed, shared across agents):"]
        for u in plan.skill_uploads:
            lines.append(f"#   {u.display_title}: {len(u.files)} file(s), used by {', '.join(u.used_by)}")
        files["SKILLS.txt"] = "\n".join(lines) + "\n"
    return files


# --------------------------------------------------------------------------- #
# google-adk  (preview: structure + audit-annotated gaps)
# --------------------------------------------------------------------------- #
_SANDBOX_TOOLS = {"bash", "edit", "write", "glob", "grep", "web_fetch", "web_search"}


def _ident(name: str) -> str:
    return "agent_" + "".join(c if c.isalnum() else "_" for c in name)


def _py(s: str) -> str:
    """A triple-quoted Python string literal, safely escaped."""
    return '"""' + s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"') + '"""'


def export_google_adk(project) -> dict:
    g = CAPABILITIES["google"]
    out = [
        '"""Generated by `agentlift export google-adk` - PREVIEW.',
        "",
        "Maps the neutral agent folder to a Google ADK / Vertex AI Agent Engine app.",
        "Inline NOTE/DEGRADED/UNSUPPORTED markers are the same gaps `agentlift audit`",
        "reports for Google - fix or accept them before deploying.",
        '"""',
        "from google.adk.agents import LlmAgent",
        "from google.adk.tools.mcp_tool import McpToolset, StreamableHTTPConnectionParams",
        "# from vertexai import agent_engines  # for deploy()",
        "",
        "# NOTE: agent models below are the folder's Claude ids; on Vertex map them to a",
        "# Gemini model id (or Claude-on-Vertex) before deploying.",
        "",
    ]
    # roster agents first, then coordinators (ADK needs sub_agents defined first)
    roster = [a for a in project.agents if not a.subagents]
    coordinators = [a for a in project.agents if a.subagents]
    for a in roster + coordinators:
        out += _adk_agent_block(a, g)
    root = coordinators[0] if coordinators else (project.agents[0] if project.agents else None)
    if root is not None:
        out.append(f"root_agent = {_ident(root.name)}")
        out.append("")
        out.append("# Deploy (preview):")
        out.append("#   from vertexai.preview.reasoning_engines import AdkApp")
        out.append("#   app = AdkApp(agent=root_agent, enable_tracing=True)")
        out.append("#   agent_engines.create(app, requirements=['google-cloud-aiplatform[adk,agent_engines]'])")
    return {"agent.py": "\n".join(out) + "\n"}


def _adk_agent_block(a, g) -> list:
    lines = [f"# --- agent: {a.name} ---"]
    # sandbox gap
    used_sandbox = (a.builtin_tools is None) or bool(set(a.builtin_tools or []) & _SANDBOX_TOOLS)
    if used_sandbox:
        lines.append(f"# DEGRADED (built-in sandbox): {g['builtin_sandbox']['reason']}")
        lines.append(f"#   fix: {g['builtin_sandbox']['remediation']}")
    # approval gap
    asks = [t for t, p in (a.builtin_tool_policies or {}).items() if p == "ask"]
    asks += [f"{m.name}.{t}" for m in a.mcp_servers for t, p in (m.tool_policies or {}).items() if p == "ask"]
    if asks:
        lines.append(f"# UNSUPPORTED (:ask on {', '.join(asks)}): {g['tool_approval']['reason']}")
        lines.append(f"#   fix: {g['tool_approval']['remediation']}")
    tool_lines = []
    for m in a.mcp_servers:
        if m.transport != "url":
            tool_lines.append(f"    # SKIPPED stdio MCP '{m.name}' - Vertex needs a URL MCP server")
            continue
        tf = ("tool_filter=" + repr(list(m.allowed_tools))) if m.allowed_tools is not None else ""
        sep = ", " if tf else ""
        tool_lines.append(
            f"    McpToolset(connection_params=StreamableHTTPConnectionParams(url={m.url!r}){sep}{tf}),"
        )
    if a.skills:
        names = ", ".join(s.name for s in a.skills)
        lines.append(f"# skills ({names}): ADK Skills use the same SKILL.md spec, embedded at build "
                     f"(load_skill_from_dir); update = redeploy")
    lines.append(f"{_ident(a.name)} = LlmAgent(")
    lines.append(f"    name={a.name!r},")
    lines.append(f"    model={a.model!r},")
    lines.append(f"    instruction={_py(a.system)},")
    lines.append("    tools=[")
    if tool_lines:
        lines += [("    " + tl) for tl in tool_lines]
    lines.append("    ],")
    if a.subagents:
        lines.append(f"#   coordinator: {g['subagents']['reason']}")
        lines.append("    sub_agents=[" + ", ".join(_ident(s) for s in a.subagents) + "],")
    lines.append(")")
    lines.append("")
    return lines


# --------------------------------------------------------------------------- #
# openai-agents  (preview: subagents as agent-as-tool; loop runs in your app)
# --------------------------------------------------------------------------- #
def export_openai_agents(project) -> dict:
    """Emit an OpenAI Agents SDK script. Subagents become tools on the coordinator
    via ``as_tool()`` (confirmed working in experiments/subagent-composition). The
    orchestration loop runs in YOUR process -- the ``emulated`` subagents tier."""
    o = CAPABILITIES["openai"]
    out = [
        '"""Generated by `agentlift export openai-agents` - PREVIEW.',
        "",
        "Maps the neutral agent folder to an OpenAI Agents SDK script. Subagents become",
        "tools on the coordinator via as_tool() (confirmed working - see",
        "experiments/subagent-composition). The orchestration loop runs in THIS process,",
        "not OpenAI-hosted: that is the `emulated` subagents tier agentlift audit reports.",
        '"""',
        "import asyncio",
        "",
        "from agents import Agent, Runner",
        "",
        "# NOTE: models below are the folder's Claude ids; on OpenAI map them to a gpt-* id.",
        "",
    ]
    roster = [a for a in project.agents if not a.subagents]
    coordinators = [a for a in project.agents if a.subagents]
    for a in roster:
        out += _openai_agent_block(a, o, is_coordinator=False)
    for a in coordinators:
        out += _openai_agent_block(a, o, is_coordinator=True)
    root = coordinators[0] if coordinators else (project.agents[0] if project.agents else None)
    if root is not None:
        out += [
            "",
            "async def main():",
            f'    result = await Runner.run({_ident(root.name)}, "your task here")',
            "    print(result.final_output)",
            "",
            "",
            'if __name__ == "__main__":',
            "    asyncio.run(main())",
        ]
    return {"agent.py": "\n".join(out) + "\n"}


def _openai_agent_block(a, o, is_coordinator: bool) -> list:
    lines = [f"# --- agent: {a.name} ---"]
    used_sandbox = (a.builtin_tools is None) or bool(set(a.builtin_tools or []) & _SANDBOX_TOOLS)
    if used_sandbox:
        lines.append(f"# DEGRADED (built-in sandbox): {o['builtin_sandbox']['reason']}")
    asks = [t for t, p in (a.builtin_tool_policies or {}).items() if p == "ask"]
    asks += [f"{m.name}.{t}" for m in a.mcp_servers for t, p in (m.tool_policies or {}).items() if p == "ask"]
    if asks:
        lines.append(f"# approvals are client-side here (:ask on {', '.join(asks)})")
    if a.skills:
        lines.append(f"# skills ({', '.join(s.name for s in a.skills)}): upload via the Skills API and attach by id")
    if is_coordinator:
        lines.append("#   subagents below are exposed as tools (agent-as-tool); the delegation loop runs in THIS process")
    tool_lines = []
    for m in a.mcp_servers:
        if m.transport != "url":
            tool_lines.append(f"        # SKIPPED stdio MCP '{m.name}' - needs a URL MCP server")
        else:
            tool_lines.append(f"        # MCP '{m.name}' ({m.url}): attach via HostedMCPTool / MCP server params")
    if is_coordinator:
        for sub in a.subagents:
            tool_lines.append(
                f'        {_ident(sub)}.as_tool(tool_name="ask_{sub.replace("-", "_")}", '
                f'tool_description="Delegate to the {sub} sub-agent."),'
            )
    lines.append(f"{_ident(a.name)} = Agent(")
    lines.append(f"    name={a.name!r},")
    lines.append(f"    model={a.model!r},")
    lines.append(f"    instructions={_py(a.system)},")
    lines.append("    tools=[")
    lines += tool_lines
    lines.append("    ],")
    lines.append(")")
    lines.append("")
    return lines
